/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    makePlayerMove
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_JNI_makePlayerMove
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     JNI
 * Method:    getBestMove
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNI_getBestMove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
