/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    initAttackTables
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_initAttackTables
  (JNIEnv *, jclass);

/*
 * Class:     JNI
 * Method:    getBishopAttacks
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_JNI_getBishopAttacks
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     JNI
 * Method:    getRookAttacks
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_JNI_getRookAttacks
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
