/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI */

#ifndef _Included_JNI
#define _Included_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNI
 * Method:    makePlayerMove
 * Signature: (Ljava/lang/String;ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNI_makePlayerMove
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     JNI
 * Method:    getBestMove
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_JNI_getBestMove
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNI
 * Method:    playBestMove
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNI_playBestMove
  (JNIEnv *, jobject);

/*
 * Class:     JNI
 * Method:    playBestFromFen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_JNI_playBestFromFen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNI
 * Method:    makeMove
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_JNI_makeMove
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
