/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testFile */

#ifndef _Included_testFile
#define _Included_testFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testFile
 * Method:    maskBishopAttacks
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_testFile_maskBishopAttacks
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
